apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-basic-secret
  namespace: infra
spec:
  encryptedData:
    password: AgAy+R1hPEIb60I/sIR7+w6eBAXHmXCCBhyRQ49sTU+3pWiPI3m5WG5/AkNufPWTuU1OLKv6t31N+AUQvqCAarCGkUOnzwRToZbws170lt1XTIbkF2VZkL6VTu4FTr4pJYptEFa8Hg/D/rozRlE8m5Iw41/1cOhnHZcX+TIJpCKEwplApSDA51oEwQ1sksgNq5WJ/fX3CTLA9U0VufPKw1MftHAbXqr6xHMqWFu9TgGIBQI0XP72+X0ygASC6MvQoWI7nvkxNZP3HF7u+jApYuOeTZVsv1oSmu7dBhki01qMjDTftVCYsMhklTXcWvMGaUFKKK2Ouo4xSP0BCVZsx5tlj28xWvu6wtErEY9QGqA+RveU38aApgan3Auyh+4O+5Pm2/vMl5Yz+SCYyaR0CuS6o28m6Lo3ld7d3t7RdCI73nduL0mWXYTqABfzbVlkdGurnFiBpLsZPu/Q6NSCmr2y3tYlVHWMT2CwAxcgU9pAFIVjDwphecqUiShDsPPfjOkExUmxJKZZQ3Ze/e7cXqkuyYIJGVAvejMwVEbgSUdB9sLQMWGZLiVjQjo7uGTCzpQqL4klrwY5YN64ROC12NLVXgyNGONZspL5dQLwn59Ocf1lL5RtFDBczhG2m0sZ1U7RZ0xhOLzNNGQchPbUkR3v0R8dmhf65xU+W7TszEZCzH9oSgcograReCW9/yYURfTqcc/Rqk6WXzbMxMqehLtsRzi8lt2B9y/ju/5Vgsqw7V7uLDDMdTHiZVFK01oHDdGCskJIiwGWJRJoXDUyZl0CuuK8nfyGz75b/a9DgHXIVqBdGTfBTU7awNzMWTo=
    username: AgAzc8Qv8RsHGl4EYgU7FNnpbxfmdLth+YbbNV37zBqDKLuVtISDReQIncaWAdqsim4wG9pd24LHlZ+bZFRXF7uDHiMmxqGPIaTB8nI6b4kDp7iCjGicOGnwCFlI65ttarcF4QftQjksEwD+vi+Run2bRbzZr1/N+pNh8zVMFYuYsQbiHUKg4uqXLosm82MMwyN8nEyXzlxc0SIFlyEPiY30NlYDk8gz18YYNQFXDctTziWsmBQmtmGVrM7BY7Qm3soBqAuJ+5kArXcR4knoIOuceyaBIPNQBDRAWiUbzWxIxUKEzcsQ2xllteVrCufbwBavJSlSpJ7pvrcwaP4kbwDfsA1nHI7N3D0tXmkYKedU8SYQDXHzNPYhgWRpfbe1IaG6YnH5ZJ78XqnyhzC09nGMYnJFEjU6JBcvAF5KMv8Dvak0pAMmM44IsYatyhXeo+6iJAEcpbpVesxyoBJTaQikBwPvladzrswrPw7SsdCExnHEc6zKjf2lZStuixvWPMnd035JJPS65eviGGwO6QyhjKQfKZwPWoAm+BnX6dek5Nyxwh4KV3HXaSIrUlmMXXwtbmuF8Qkrq6kiBXvM2qqMPZf1oCdXBT0cL2cXTBD181eJZuRAQbQjAlj2DncrkwczbSO0xpa4Wbvb5jXagD0AwpPsDxI5arLSKkQ18FDnGLXWAmU4qyZMh68etrspQgFhgjREQAkcZ+g=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-basic-secret
      namespace: infra
    type: kubernetes.io/basic-auth
