apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-basic-secret
  namespace: production
spec:
  encryptedData:
    password: AgBOi2j/YxUeoU1m3c8GMSpLchuWkZTRd6z5dTCbJUzgHKkqVZPbnAnz0uiU7hl4s0uSo9k1gsTkyrI7/USAMJc2kaPISAD6HUwUkooQrdhwDpI0yVHs+sayGdbPsH2EBLP8tuQTi3EZGwUfhobmtqJX6Mw9pruP0NBTveUxjlfa8mtrTqnRYcOCq5qpWiPfVGN3lAA0Rsm0CKlGDOhzwYCufqwtmCqio3t+Z74T6xMewXbqJRA13lMzqrwnE9xbOMyj/tSIIsnEaq0iiEA2gMMG1Pqyhjm9ioKyy4XAcGbjBYWRhuO6ogS33H+Oitv1o3cC2rjaQGQ9Gitu9baIrnk2c10sdFNYnlJJDgbbBr4VOsOrcPPvOzGL7wljNdp7NQ1a8F1vVMUFat0ceXdOdXBrZLACfQnCOS2Yvt9TsnBZ74glZ+W54E7ZtmK14wIenTAwHUpKTh0QdMyN+QsOVd6QmkcbAqR7r93dFBlZ1eY879/0fD7XpIRfnvJUKjgswxFBCfHGZGG3SF+vNwr7tLNg51F4lbDpO/L2tFxntdUXv/JmMkdqS74JNLFVKOx+3hWsjLUubjM1628PLS6lmxph8gaqzSY1DsHpzUIzO5z37MsBNJFIL5b0StjRXaFIomqkEL+7UXy9gyFyWG7mzLB/1PISLIWTfW5BFbAE8NHCX/x631F9VaH7+G2h4VfQIlzin0kEGfJqTxhZevBMYCumCXpSwutLiu+lU2NM1i3EqBo25bPS7aVEraFb5oUStPyBkfQdI6xaFhaKd7IbW1tW+eC4SKM7TKkbUJJFVlsSp0ZtKU1kJr4U+DDfBTY=
    username: AgAuBef4lpyaAJHOPh1/cuLvxB3mVRaxalu6H3+bnwlwLk/44vP1JoNwva4aWf8atYnl9yb7d2rgiZTQP2SOG5DSqED1pPybOPCTp9OoHC/FWMCPSoFauTkxe0JYEt0+Jnbd/fFZA0jwi8bpjsKphi2JbRAUC4LfRkc8msVJpD15r9OQ+pUqzlPgOwgO0viJbBE0xbwF56wuRI+vLuU9HmQJtK73ACXHv4MepVSAsbXrL3amHhQYGjJvI4k7VHtZQe8ZiKBvffbiTWr0y9YhsI8kfhll6Q8PZdI/hOu/9YsN0GhWYvAVRDoX83hnA/lRny5DkmlZWY1da5ey9jqkF2DmqLBgU6ZsKtgEdwl/i7jKIa5szOEDczpgUHTdfj7PNaLqKxD9wCGds6XUO5HczWjqBB5X2PqO95yyFQxNbQSRLE4IokhGjrGu0Mv1lflIlhABB1oRkgDKtGFrIAUQ8E6qrYKcvnG7QU7VVAuAgKtRbhbWwdusaKjtdE1+n4PlkDK/ElTQo6r+Q4KPD9v3KIS0cGmqXl5nXneSgvCCk9RCao6HGWxTrrRqdimmAzYX2laCmeA6KPMm2weOS3kbYvO+rLLgNl7VlYeEal5TsEG8ra3P17IzU5wBwMbdwr410+aTeqHxG+18JvHtpNp8aL7Vp8iokvk9d6JvJ5Cx7YBlgV84+YHRG6G4zLYjv5VOtTc2OY6jriQrzck=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-basic-secret
      namespace: production
    type: kubernetes.io/basic-auth
