apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-basic-secret-production
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgBcnr55wslCJtbHtoXyfJuNgE8saXKi00ePr0MKJ5fa1bQadPGGU/jetalMu/CJzZnXXPfri7XYvKzcftoxLPeXDQZTGnX/Desje/mhCk+u+4ho73EO5Hl1j0GtjCn+Z68JYCpMV9lJd+juvR8vbPZjC6mdlMnvZibkMNoWkRZizCM+albinvyYAW5SFPhMa5TuslhNY4u0SBi98K+ix23KHl5VDrYfo5Q3Gyd4d40wR6hSMKX4vrANA7S1QDZWSFqTxlid2danP9N2Vqe3CqLLr2PHdCpwTOAuVyenm6Gi0JUVH7Io35XZbGZhoDFReDTusk9xM4RKCN4ZISpDbEOJvmUJyrPIbr6/joD/uWeM+t7JvpS6JtJwOwXHtw/m9PtcMr+SQiwuE2RQSPIhSUaecexlypFmk436ylNuCP8KTfGQhUQLOr+xy+glqO0MvIsabHMAf+RF9mxiIpZOTThwolGp4Jv3hK5OHmc/d3pKOF/iy/2dOgKOzYi2kRZsQoJSHzCAUUukhkuxgLRxOPa03crRoACGsSYfyMlVaZbTJeTNTt6t6rE4ZSEDWIf00k/9g4w4A/cv3hfkFM8/kv52HDnqIt1MymMuttdFYwDjEcXoxixhG0yC5nC/tYiS3FGZqaGnb/I1y9W3yvZTo73+ykBv8fAmdMZjZ6C51hQv1/soCRSURQvuVXIBTFzsCnE3UkM5Te9cSagkClJQZeoIf6gx9cOIL4zxbWDC8RhemchUXKWbOk+5/AJaadratSvoPQRpkLG2I327vKd7BTC1j3LAramwLBJAQ9Vuc44b43OVhLrNwIPymL7pGwaC1S+Bjs1hqW9IiSSQBaSe3tvZI5bNTftgpDjgzUmSPiuhAneWB5QRCh6yc7HEkqy/UKodNSM0MNG8ylG5FGUYGPc+ntnni4XIY0iUXHahfekOhYhe0xhl6mKNeFLNGFbbX5kY82QWdcIy6vdIF45IHtA=
  template:
    metadata:
      creationTimestamp: null
      name: image-basic-secret-production
      namespace: production
    type: kubernetes.io/dockerconfigjson


