apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-basic-secret-production
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgBaw/0JmQPzubICCTHZuiH7suEbj2t3B/p6Z5VIn4lkp1Yhk3ODp/sn9wtYvvMypwU5ktaaLJlkuh/CEwSMsCMojKkLjivF0g7lhIBV/yNCRlgMGrEFmXh2f5CHpxhSteaL2O1dFryLa9gQIOT+P8tacUCeSUtrsVGkNH9AuOiZJczuCDB6ca8Dv+sXt6G5ZUTglPIHu+czDWH8MJk8AfIdOW6uN2vtIwS7KmUcWQAXhU31g7EbEdToOYwFmDCRRTnV8F5HxbZKsf/ngh7LTXFCOvoavuCWwJFzu6B6qXcr0WzjWbBtvc7HUvYd9SvOg+y0rtfwKu1c3TpXvt9Ai8F84gzVVyta8lkq3BKXkW84KCBf1ia4vAXo6pAyfsdNhjSpWcWX7mr+LM/ZABsFXZeZzV1eP3iv5onYcPIi/MzCOu8j0+nufTh/uDza7EDoPXcxcV/lGb8PleKEYd09YVkeKpSVj5HrWlpN8hJBbJRwn6TJVxqed7pZpvQyHMqQ7w/KrH5n8A9FDwW/QOGVvZBxKA0GOr40aqj0n+sy7mFTUi08shC0rHokzocJ2BeIkbZLGzmZB4IZ7ct2X4KbE24BhdZzUr5jOEVgIPlC8lWjXGW8C3cVBxd81E4nhkOT8c1UO7jvzAxvG0nhdNRdKJx1kXXUcv2Bis7l9ASs00kmrhM7f2sNUtjt0x0hJZVawQyrunbX/ArE9L/XXzPbgBX1nOuel20s0y2+zlfL7ET66T0WFJoGgKFeFOHP3uQqd3Ub1PQtj+G837dIl6nWSQjBj1CyYQ7+I5KAZGiPxwGAQzi2emu8JDZG0nYCcAjPwkfZ2ZZ4gHilJ8n0WBBrQ3MT+prkTSS9T2OnrsZjTKWHPak/ZHfH1pvhOiT39tlFIPH6cCEQWz4nI4F4Cw8qMMiv33FsXsQZkLtZNKalkzSMzV4ap3IZZf/XSmqualvIy+c+UWnUd1ESYlggqQ0HwtU=
  template:
    metadata:
      creationTimestamp: null
      name: image-basic-secret-production
      namespace: production
    type: kubernetes.io/dockerconfigjson
