apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-basic-secret
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgCZF7bZb9gOpznliLJ6ifpsy1P/8QNGm8W1VesX9p3mR4k3BA1JmrurUY77rsZjbFN8+y13E7MMHvCVqDMBHIpgUuIrBts1TM03Pc7iJaU34JF41GrFfsqO8iXa/PHlQ3LfD5vuedINJhSPerRGF/6iTA3ahRMTWi/UzYFAcip1ABVQirPO5ffrGE5lJxh5LO4ZqbLiJMgw0oTiaBnAUyRl2lK2KuwD8LYUHOKeZk0JS1fE7/kpoIfvndKUwaT7Hx32LF9GW9VaD+E+BKPLvMBtj0HkPE+K1L0BAI4GX4vnACNNYqXeJ50qYAW1iaYY32Dm0/efGhzGNtNcZxIlXuhylOJUV6KU/XT5kHra/6QGoXqxIfvfScjiBlPSU2aAwRCcSGTYxfnoCLoQsS+yNQG34D5OHJUCPfr/QGfg1503xSDshz+l91Jl+2CnJHHqfNmUIWKa6WWBpCM4zyHy9PhzRL7KH9clqhdyA69/s9bU4cshtqDEMPE1iZoVCBnX8olvYRa5ZBfVfc6RpMTCCF4kO1rPCeVhwjidMyrLuVyG+mp2RBZB0YynWsLZGGKvYOkQo3+wdUlBsdwdpmayhmXS16JNw6ZS6Ny1NtLCWHGi8Re3Zb+SoT9mlKldZLTZrlMJzMQ5fpR8cTqgFU2ThzHTHe6/A8PCmhb6KPsitfwGnN7Vjsju4Pf29DcSo9p9KJFUeeaqFkZaWPdmgA+XskcD787Zx/XJHX8voMGje8ylBlDmIgYK2M74J+WBqEPPFnpls8tpSWiblKn2jXupyMNQt8uOJKhnlW13iokHTLKn/UxV7CEZcQkFG/q8DrE2YwzBI6kPWVUN2mahHwCBOmEqLAevntvdOjmLoliLzwmql04EBQiJUqZnqtZHf7CCw+4wA+EUzh0EiKImJRJRzKlBqCTF9wuA8HotoOoBWmeuWPlI71QH7y0lY2/w6uPlQV5c1sjXCBGB7nwsnVPvkbQ=
  template:
    metadata:
      creationTimestamp: null
      name: image-basic-secret
      namespace: production
    type: kubernetes.io/dockerconfigjson
