apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ankiba
  namespace: infra
spec:
  project: ankiba
  source:
    repoURL: https://github.com/unimarist/k8s_manifest.git
  destination:
    server: https://10.0.1.185:6443
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true 
      - CreateNamespace=true
