apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ankiba
  namespace: infra
  labels:
    app: ankiba
    environment: staging
spec:
  destination:
    namespace: staging
  source:
    path: ankiba/overlays/staging
    targetRevision: staging
