apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-basic-secret-staging
  namespace: staging
spec:
  encryptedData:
    .dockerconfigjson: AgA//bOmWKjAXgr2dKQNDjRGOnFZCxl4VmHLttgoYdVOcrYhF4fDITRhIm8t6LqIpqo1xrZPFtt8a9gBAtLFDxnYruDsvMMlZns+7pombNTGg6H1eeY8DXNsUkg7VPHQAcWH2TdMVOryZE3BNXJrNCtj0ztGkfnSocsK4KW2T0dEUq+dvlLDbuJSmA+q1xwdEady5ZV+ry7U/KkAvjcVJcJ8/rSv/2iW5s8zjYWNpnp0UQW/dB4OceUzQubYkYjBLGtr9qSL4+S9rjkgieBuNDVn2tqUYCb3tFO/yNaTQZ7aTthAaIvRbAPbjra9BqK3WWIXmVSz0bcNOcRYOJBx7y46bfwA9ypLCVWf7o7rXrq+YgKcpLaoUAj5Tjq2sC1wBJbs8Jph2s8fd/mLnKyLSAE3Kj1Ka0+2So+3+oGIUPZHcpULPbO5eq08yymOD7K5fBr2TauIMbRt3GNJpM6HFXXaPp0+K4SIvQlslh3t6DhoqLSM6mb3AgkiaXHwfTYsyu3No6qnEXnGh5orSpJo/g5FmIreprPE2rqILUGZYPmbQuQbmUFxJm+3er2SzAMMWyxttt4EVAgSZBR98IHctgOcu9o9nIZRnt5klu65QT4cE0nw7+qMzQG8QmySwqXjCqmW/t3hCDTLCT3zo2KzoTRWro0XWExwAQ/XLXW9UzbAJYM+1z4jFgsd/77bAp5T02XUC6Dt7Vh6b1WLZkQuQeDuQB+fKBkP+S3FTWZxOo9Z6IaEOQU4Plsvm2+oJjihuhAQ0W2Q9NDSac+cTPoLC4VZRjVFfadQe42bjb7+2AFv4HCUZ0Svj7Uiqf0nMzHZzeJOMP0NfS7NrlFkboXB7NVTuiEpaE4UqZ2xOWdG4Yaj2O5S31i0rf585o84QsVwfS6+pz36bO75mjHMwcKv8iBDSW37WgI+egRH72cr9xquhf0xOxCsBmcyy5kCiTXxu1sC8wxDeOaZpsB5zRX4N+c=
  template:
    metadata:
      creationTimestamp: null
      name: image-basic-secret-staging
      namespace: staging
    type: kubernetes.io/dockerconfigjson
