apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-basic-secret
  namespace: staging
spec:
  encryptedData:
    .dockerconfigjson: AgB4uIqpPuHpFRclimqF0K2V/ZqEQO4dAuQWb8YXs/E6Qv85zEjG9Ok15CCIZ2fUdMTVq/gTQPAEcPU/GLhPPBkRo5P+N0uhuq+wdjPF02jDr7Q8fIVJvJEiLXNnRpELvwyDWxKDk/G1w9Ss1KsHxoTS1Xwg/V1GKQmWxnzC72LwEIvoIsLlT5ECIjlwDgI1qBBzBgpCd2KD2K1o8RX8Nb05KIcGQL9CKcRO4a1nFJYPfkGnKFoksspROI3o/DBlJMX2m7R4TVmYgEfJww4/0eCmKObMfO6le/2kw4PbxYXocbIXZXTgrDQOzyFNq/lfEJFFgJb0IURhD77kLfO312WNsVuqbQloUdaBBV72yUiEtMvUPT0ugOLVahTCni+h1vGg8PrTgfIq8BXdsyFBIRw1qr5H7hy1Hv6t6MRGhVFT1xQw4yeeLc3nnKOH2fYrjuUL5uaAhn2euze0B0IHIkduHWDW8OYF/ikwu/6srefFddRS/wlSZ+b/2zoKCVlhhoQ9BYNp52pMJlAalDhPuRUeChmPeh8WI75db1sMeLqpknJLQAN65R1szrWpONSXsZg7qW6TSjWN8VdKeEi3vTlg497MzckIrCWpCawQVNgMXuq7+54/nXLf4D3McoNu7Qq5JzDO3aaCuu2L3IpSfHCUiLTexsR473p0SfC5DyujLzLTwkx6ZfbiJ1yrx53CzvjsgDmxXn5tGT1XS0yQ57h71gJ0plGXLpxatvlw3Vz7MF3YAzcRhZ4tY5UdL440GAK+XWpZR8AytxDhQYHXMsGwPJpkfxCB/jkyBOZ7Se5dMUT85M0uJT3myclPL+5YItSpV7ChpvZQ+3esJkx9NJU7AdX5nTxqHQ93UG4uocZOzIpaIOn/KVoBgCqcEJnngTO5Nx7HZvOZNUW4aKRCBT6JBf8rE3jJi2xOI7ouuPVwZ9mBTmU7cxtzuPqpYZ8wrFN9pyv1n7WzCMcr7hy0UWw=
  template:
    metadata:
      creationTimestamp: null
      name: image-basic-secret
      namespace: staging
    type: kubernetes.io/dockerconfigjson
