apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-basic-secret-staging
  namespace: staging
spec:
  encryptedData:
    .dockerconfigjson: AgAFK5OMS730yG+CVcF3wimjVYUo/L3dwp6Kydt9NQxWBVAP08QHhsnKzY9CsFD2dJfPAbDj7ZKZLtfKvg/JTuEN16EcRX0GUi2c2gAnxSdTafA/vm16F7fIYRrMuunYxt+Q3+TrgLSVW7ou9l7S9mEYiU2BxTGN0fgBoY+b6fVDJhgGbJf+PgAkOC8VSJGMnOxRQ+5ExIoBbC3PRJYYnj04jEU/1PIvvrOtnchhrCfkZ3gbGHYp7MeYXEb88aMsx6uBcE7NtQv+I36ipnbPiCQhkckMAhcitu+Y9bkCDN00J2WPa/phnlDb0Xng8Q2RxlT9iDuMjeLQ7xGG+ViyWNvzWHG8bdAPQTIyPZil2YhlcEbfvLeIcctxQylQm5NltWgHmhCKDolgvaiJZvurbpySmnxUsQh5fwA5ps8MlxT5hMBGeiOmLdj5azWgq2xTP9zwvWiAn1ABzu7tDeU22+anCO2GGgApJeDSxtmjK3o8qOtJ4c/wBnXGRixj+78XZ4Rr1IlVYMn24U/nWMF9eIs3gxmclSq0DgtmwdvQY+L7akeFOX+8FrjObyUfQogODikyHbPDRMlyCHB98TNgd2T+SST8/U6jQ4+USYDtTRaJ0BDWXroY7ADu/xr1YLS9AFDl90AB7Qhprm90mYDq82nxIE8UEOxiYqSOJ4VxVMFYgPunQyhcgH1y0z5fYODc6zEMbulloAqL600fKd1w9KC4M12Oo7Hd0u1qYgzJ+sjaRWRUhVwQ949ggYAZLlWQRPmQJz/m2+PSqd/Ga1hg5mcs9zabD9JQm0ERFRGkZIRf2bN8/3PhJvPXh4JkS2AiA3wXIX5BhlOVRqWiSL6J3M33swEN0RM/SomeVL6sbHYXKVpMcIzAHhExuY44QO3+nBwMtQVHzKNnuZmuO4rriNRhWjstw4afIYGzpSAc9MQHilbUSPBQiI9y7wvY/tq4D7upaE9ZMlvRkmiwUoSNDc0=
  template:
    metadata:
      creationTimestamp: null
      name: image-basic-secret-staging
      namespace: staging
    type: kubernetes.io/dockerconfigjson
