apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: production-user-rolebinding
  namespace: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: User
  name: develop_user
  apiGroup: rbac.authorization.k8s.io
