apiVersion: apps/v1
kind: Deployment
metadata:
  name: ankiba-ap-deployment
  labels:
    role: ankiba-ap-ENV_PLACEHOLDER
spec:
  replicas: 1
  selector:
    matchLabels:
      role: ankiba-ap-ENV_PLACEHOLDER
  template:
    metadata:
      labels:
        role: ankiba-ap-ENV_PLACEHOLDER
    spec:
      nodeSelector:
        role: worker
      dnsConfig:
        nameservers:
        - 8.8.8.8
      containers:
      - name: ankiba-ap-ENV_PLACEHOLDER
        image: ___IMAGE_URL___@___IMAGE_DIGEST___
        ports:
        - containerPort: 3000
        env:
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: ankiba-ap-secret-ENV_PLACEHOLDER
                key: RAILS_MASTER_KEY
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: ankiba-ap-secret-ENV_PLACEHOLDER
                key: DB_NAME
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: ankiba-ap-secret-ENV_PLACEHOLDER
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ankiba-ap-secret-ENV_PLACEHOLDER
                key: DB_PASSWORD
          - name: DB_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: ankiba-ap-secret-ENV_PLACEHOLDER
                key: DB_HOSTNAME
        command:
          - /bin/sh
        args:
          - -c
          - bundle exec rake db:migrate RAILS_ENV=production && bundle exec unicorn_rails -c /var/www/rails/ankiba/config/unicorn.conf.rb -E production
      imagePullSecrets:
      - name: regcred
