apiVersion: v1
kind: Service
metadata:
  name: ankiba-service-ap
  labels:
    role: ankiba-ap-ENV_PLACEHOLDER
spec:
  ports:
  - name: unicorn
    port: 3000
  selector:
    role: ankiba-ap-ENV_PLACEHOLDER
  type: ClusterIP
