---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aws-cloud-controller-manager
  namespace: kube-system
spec:
  template:
    spec:
      serviceAccountName: cloud-controller-manager
      containers:
        - name: aws-cloud-controller-manager
          args:
            - --v=2
            - --cloud-provider=aws
            - --use-service-account-credentials=false
            # Set --configure-cloud-routes=true if required by your CNI
            - --configure-cloud-routes=false
