apiVersion: apps/v1
kind: Deployment
metadata:
  name: ankiba-ap-deployment
  labels:
    role: ap
spec:
  replicas: 1
  selector:
    matchLabels:
      role: ap
  template:
    metadata:
      labels:
        role: ap
    spec:
      dnsConfig:
        nameservers:
        - 8.8.8.8
      containers:
      - name: ap
        image: docker.io/manmaru/ankiba-ap:latest
        ports:
        - containerPort: 3000
        env:
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: ap-secret
                key: RAILS_MASTER_KEY
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: ap-secret
                key: DB_NAME
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: ap-secret
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ap-secret
                key: DB_PASSWORD
          - name: DB_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: ap-secret
                key: DB_HOSTNAME
        command:
          - /bin/sh
        args:
          - -c
          - bundle exec rake db:migrate RAILS_ENV=production && bundle exec unicorn_rails -c /var/www/rails/ankiba/config/unicorn.conf.rb -E production
      imagePullSecrets:
      - name: regcred
