apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: aws-external-cloud-provider-example.k8s.local
spec:
  cloudControllerManager:
    cloudProvider: aws
    configureCloudRoutes: false
    useServiceAccountCredentials: true
  cloudConfig:
    awsEBSCSIDriver:
      enabled: true