apiVersion: v1
kind: PersistentVolume
metadata:
 name: tekton-web-pv
spec:
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteOnce
 persistentVolumeReclaimPolicy: Recycle
 nfs:
  server: 10.0.1.76 # private ip for common-control-plane-node
  path: /tekton/web
