apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-basic-secret
  namespace: infra
spec:
  encryptedData:
    password: AgA3oza5CdDi3DkWc4oIll3A64pESP8v7YnICRBciQThRIZ4djG9keJuUVKcrK2ae/xpUGRS1+/zsAbHclKDKJOchLlsXRNnSZmmjJEInTus2KtgUQIUdR+g7l+cQbVS0KWrrcakBvcmH5h4U++mkXyO0UWpOvAmqQ9tPTDc1l21umBA8NbA7/8aM46g+FXl8ouqqV3c3ijv++gt5sCsf+/MyeziY99DhZV2jgCNoDFZp8zhnADHAn8ftMH01TdjMHh9DjOyDJxj6WnSJPDoBnz4awY3cy5vX/zLEjk3RpLWgdOiDYKcj4HiL3xRo8YbcJQxmUE1s5hf9QPGGJ08RVWym3w9+s8ODFQwm0kAl6RUAr0yTPTMruIgFIZyDILpYadJo+Sko6oRdra2D3MWkbq4u8RbcCgCxLywihTs2cTLpfKZrJsqa52EaX4MOexxlR2qkhiDIMf8I4YglNvOnszjKNJrZwir0rGn4dxnMFhykJtTX6VAvyc35j8c4+aXfzWPpIAhXxEtFAssm0VQogO8y34qrLi9N6CQsnZJgmdPdnL84GJahmV7yCZXNvGhoeNGw3MpAD9qfZoPf/hSjBTRlg8z3GV9XN3pNY7ci5EYMm3k5M5/J8ln8CoRwQEfeyvJpDDlj4R3hhi9rwzu0J69tx5dIzdkmmu1wNaGHAf7ZTXlMKh0bLGykkT3OHOZIhMmPvy6CiReOrw7M7yjspjYwXVWjz8NZuq+uMOpjmRT9+XCc+TasO25fiUqgcSj7B/AmUgNn8eksxrpSArZHjECkKfsYZnn8zofbdju4k+5//eMtb/cOOyHiiWMgjw=
    username: AgADwuj7NOKuq84KeZD00rUrs14Xy7Iwa9Pc7BIz/NFF53yU58NAKl1DEX/xP8V+ul6J+/eEA3p3i65WLMiveG0WNEYaUoFkmsw2OOROqx26qoYi9zJrIpZK4y36yxew1yhoRIAp8z58QjfiKpRj/JHHLK9wzYwkbUi0eIv9tR89kH8G77niET4Jye01CsPSG/Li+eRIZdjxda4s+wzOjIAj8uVuJ+2i0pRiJ9Yz2MahoIV+qmYX3WZe+TbqIpZvtK9waxzaNfiHyQJNuvbzWiQpVDc5ZcWvhu5K+65qDGIJ+zSZcX/KFGkrpM1YvRYRr1E6VLRDON3qfqICe8QeRP5R/IF3e6ppfeinbQGhNGwWZtG1v0FERysRZyVia6N33uYuA90kKjLrcp1CZqzx9MKMTsdFaAL+WkBkWh+Rb86+ECrQ/EQqFuEfFldIRA5GvIG6imUD/107qT6K9JTde3qj7pg6kV9x2/8MGn/72UWbh9WNKPPYH7rPZBgqdRAsFFVtuK/hBn+uQUi5zvQmF5ma7ypbQQnXpQdjnsf2Ot0o2yvVdcyayYmpXhpWKvIaFDNxhjd2oQksr40PBvbjV6tEdIzYbbwl4UEOPuhgrfFbgtk0ThsZ/TQ6d3AV7Vh8zzstji1LJJf+LKUcirePz3+i+7kV7LUajOvjyzhFpNWKQmmFwBfnq1zxcPD///WD9AGqin1y937rVMY=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-basic-secret
      namespace: infra
    type: kubernetes.io/basic-auth
