apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-basic-secret
  namespace: infra
spec:
  encryptedData:
    password: AgCc722RtDIh2+lBmz7VSCard+sLWKVkfSBj/nYo4mnvmQBiM7JYvTsQgLsOQ7oZsmzFvY87AhfhVCRmg+PDoe0/dJW2fMpeOTRjwq9fYDT67N76fFQX4QiG5D1i0heEDr6gaBGuhQrHzjutaLXZEE5SH/R7A5aG4dfWbc5sJk6BgYbjwl1YOwmRXc82la4Tm9i1DZ8qMsT2M2CxAR2VRoDoopjCKJy032iEkm2ZgaWlVvkOzK/XM693ooz24sWDl8IyKhlr/m9tJzxs9QH3rO9eZFkHZhwf8h8raE7EmVEWplrV26yJ2L1w3I3VBYpLMnQxlSaGgbqndkCAvRXIn+6sgoqla5/SSbKePzBCsqgs99yzS0n0jiIoeTLcBR2CPbHrOlNx8piw4VwifU3vi4gqshyazAFIdV7+EoSYaSyZXQWIWhXre5gLfmwIbTvhic+ON1PFckhr3+k6tStAZR0RHmigRds16MbQRmCvVAhmZizEm5ttkKdWsWXZW7n+J4hEaB7O1b1UcfBQ8hhlfpD7b50EkGCW6qquxss1+TBJ68YTz06nqAXTsl9ie/F85YjL116YWxH5KFujGdZvzFQb8xf9qdyTQP9JzYYdA2g/yRmCnGTT4nAiQsX18WXSCQqzzqsl4aOCkJsHcsd2zALGXMkwIq7dNvlElIFyogFTH1/v6eS3YOSVFcvOmMpq8h+WUcfrTRMkTPyQVbSNq+qT3NIYYrT0pgVktjaBk7KtENIdX4dJYN5IR/8bR6rKQ7gNbeQqhQ6CodSIHc3yObHdfHxEvdkTmG97fqYQ8jxo2U8plJu/jhsVmivgMgs=
    username: AgA9IjO+gUqVo331NFPaPLReCXmzGh7kSjtsy/UxenBwl39FCQttJeDfMNIWhhyIUgjHCBfWYYRuQuKqLHDCgqlUPO+GvbeIdkHzMOhVKXWZs7w0DKFPU+5f0rrKolh0wjO4alaDSNJIHknC/LmLEYp0IL0trV2uI4Vs5XkJJRcKbWmjZbVj6dFU0pNzosKwMXbNR94cN5ji6z4hhcN/PbF4qDT0/ot/eAn2eDNP+0Ouer90UZwA/E15+Ji18vPWPaQvjLpPADjx+4/mne2WbQQKEt9UMf/d3gExxvbEtW0J6DNJ8y4mv5AYUdhSDuYuSQWjOMkriku8+xjyTiHixCZnzjHAYKwfKmrlcP1s9LAy5WCabFTCjkZgStzYukZsnYv2ihhtERUw41CtK1dF1OdZ2K0xR+1Aba12RWJc1zpEhRTv3w4+9ca8Sdapxf1XRBJTgUcndcF+bLnePu0jc7z31KHYZUYTgQxRgR91K1wSv3U2Tuf5g1XHg5db3Y6am2DCswLl1IDck9VJy/ouCUYK3U47GE0M+fFa6/wpY4Yl8ZtKl4KMcjewZ6vRfjeA9AIPl36USyMucQ2fLKhEFD9azxiJEqdIGkNWg16kIWM60RvoBw5XscUe0DYCKr7/6Bfxt3PMipDSIE+oxVX8MsC1jk+bV/3Pc9bejxnsVCZ98LOLo+1jhU7tQ2pLXuFdSyd35H6CQmyMKrQ=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-basic-secret
      namespace: infra
    type: kubernetes.io/basic-auth
