apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-basic-secret
  namespace: staging
spec:
  encryptedData:
    password: AgAnpYkkad/vCFKKDdBsDBC5H4pxK2WaL1dyOj4zdbMWraVElrTn5AOwSmkwNTwalrHk7GoYohonN5bIH+wNuAXLk65mHWtq/lHBuRTB011kiywfFd4Kl/jyKKFAhx+AMzIUmNF8IgsyREUf2o3I12TxoigXVUWSkchgQt6gaF/EaIym6Esls4YHVDVtmouQgKmCOfPOr/m/ju2HhMT3M4QEgiIbfwfnL0Ld/cC8yi1oj9S4HZBh7NHEZOt3x35kUGGfOsyTFbKDpFmCKSf4aJSa1P6NQ2ZRrwJbIv5ivH1yLm99/ei1c+TJohV/+doZ2abfrk5lKpY7NkdvLK0D1TI6+24PyCFVDLTFP/bEujBcxoEnptmqBLyALGTWEjzmsC2GicFpNpman3oFZogluw0rbqw4snt/S4taJURQo0yZNJRCAGRvddb209TqdZ6UKLfjZChXo6iDmcaYI10m7Z2eBqBbr38CheTQ1PMGhg0iQLkLh0VXOzuvlH2GC8CWWrCpsUj0XIXu9PbruHunXTajnbCJFIg/MXHO02TXMTPq1SPBF+Z66PKS4GoTo3m26HtB+GRc1EqWT7M1d1HoU5vCiyyfL6SVZ0ev50PfZz+IrPdoX2P42YrztETvTdeKDIbqLEY+/ktO2bgnRItN33g9aTnI2Q4bSekrIe5TFIYJM9xeNXCgVg2hxSth7/MnWg1wiG9MMjNhlG0gKNYtCuDRPLyKaYEvH+704TE0T1SV7nIKELVZyGhMiAsSevnqg+/g4GH/asE3p0Ow5wo6SJw6nYoDsZeQJ+8w9D5xJVd3TiQ1GfxyEkbsST48gCY=
    username: AgB+M4PcpnM+IXJjEhcgfF4mlLCncG/sDRrSvxcqNOCBN3pMRqT2+9HTtGfZTccUhow3uOmbVkccnyRbd+y76AHtbdXLC6sc3Cpk9+y0EF3AHnbvBmwi/956WKNBNjrsvqFS+sAxApf2xFIkay0RnnojY0fP2VFyNHqQrtt1+fAPni/nTFgG1WmUly+fY3ncLKJKr2D+ubBTLJhG0PhmYJaPBHro29wRRQmiNFyYyBwCvmjRX5WAvgrzn5FhZkUAEupwdz1z8dW5AEIfJXSl4ahCYn+dR46v9jyj6HY2Y+/najwhWPsQPtmOlxtZUbY+epQMKVl6ukp0PJXG8KvEQ8Lj9c545wEpEHH7bFCn4oT4ZmABcWzUPZvB1kxDsO/Cap4UL0Vmni7OfbyaoKyberu9eJs6oEpFlXeERVJk3BQ+2Q+/tUR3bH3HBopfG90X56eWmubPxv9G0q8c8oWQQ2MadpHPfIfkNVk4SyakI0DXTyClwMbasTrsEGYf+en8snxoQoTegIoeWQx+ZA+/bw3ttE0Va56ZS0sb/oJDKsM1Uw6+0+Ig0k97C9h9nqwgo4CNtU4dModgzEmu5cs1tIXLA/QCo8y/6r8ufK2X1jWl9fur0yxXUtckq9dEXU+NcGCdc4ZbtKb6KfvtZvBxB5U2waxWgbWKPT03WPVxomc5I8FvDinXfmLid/xFDVrXvTvWDsHEvaEMUys=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-basic-secret
      namespace: staging
    type: kubernetes.io/basic-auth
