apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-basic-secret
  namespace: infra
spec:
  encryptedData:
    .dockerconfigjson: AgAWJABrTlUX4rK0qJorJBvu27DoRY/15TWtG2Wy+vQBgBAVyr6Za2INyQmSOEH2d1KNURDRU3Y9xfVqPciPqmy3OXWIohw2PCtJwLm5X0BAOvzQ2JycSF2+V3G/dq4VwTTSYCPfTasfTNVTMMelmR2WjbVoC93rYuy2vHSknnd+uXfV9VrFF/slCm3iap4L93AXTaLeIi9mrgl9m9oXMAB37RFJXJC7sS77XUid0fTjmfUeU/oGRTqxwrcaRT+Ssc7ZVPb/EJTdyRTUZDqeovGR7SfMZZJ/mJleRgJTKi7NBYoRr8MT1gWl14g7C2AC1mU7DbDFAQZ9mvxNYudb41hxfTYmkEAz5Kj/HZ2kGrXjFuHDGTasrVkAqhOMx91oZ/n1IGInZGLKUXVkoumkoyatdxsjMT7yN65yUnbWqffM6JYN+j9tcwRvf4E2TkryH6YN0S4loM3FOYcBwqXfDt7O4vCHsb8e1I5whrjztXn83JQKipH5Q9rv0h6UGAf/4ZPRZyb8Tk7iC2fFSMPFE//Vj2+mPF1Yw3doFouf2OM78eWZJCn++1w3wcru/H/7lBbDgHIoKvVyO11ITsZ+1kDcwOWJbVczjJm6iD/AYODYPJWViZoHYGKwTsnUVzf67UFd6y3RlrIjOS7m+m6JiLaNMLTJJtB4pFL0czLft53zMfGvbbcxXv9eLB+GwpKuit128Ad5IsZEN7kBUXZJ7T34CvCzT9HXC8Ot8RNJV/Hm8w8pn9ITUyZCtVRdE39SHXyhVi2ehdLJvvUO5jle7xx63xuTJrwKbNFVMRMYH5FXWx99yQ+NMfO802Ug4AwhaY949CKKJybevMN1et47ooZJ+zciHDQlZtV+AgvZvhmxrPiFNl0XvX+L4CwUTWJWtBrS+PcQqwJN+KQvSzzoUpJB6YTwgXDAzbxQogXtl4NtM+c1j2jdjZJTCaj4GBLW8YV9zHOAAcbxHXn8esm4h0Y=
  template:
    metadata:
      creationTimestamp: null
      name: image-basic-secret
      namespace: infra
    type: kubernetes.io/dockerconfigjson
