apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-basic-secret
  namespace: infra
spec:
  encryptedData:
    .dockerconfigjson: AgCZbOFOH5L77Ho74pBF+bdViuOxtlrjuVjcO0bfPrJ+8GOW5uFzFoesRmYkEE2Wso+vQI1+605r1+QXZU7q0F3i4TuqCvmjJsQ3Bdl6aLPBYwqkcgmWO8eF8DsjZlZTS7TKhpCJAg+6xA7xXaFevLzDiIHA6LAC3qMtF9G/MC4rzYY0rNa1ARCVJR9Fa+Yf4Pcyf0mwgf78CE97Ehooiu5otmmHwFOp2/bHU8FJ9NF8GKsMfDP1k/ZoQLjy3L/MiHLXg+DHrh57quQeSASPZUYityrhk+PRbfBmn6xGJ3PNdGYW7N/jOoK9dQ6YVXc5V0tkEwRSdWAqTglZolLh9aqtEITtzhoc9vSnCJCtqV6/psBWyyRw3Mg+b2hk5e5QXj7aAOrv0wSCqOWevp0RbVJLNYQcqCuC0kTgCH7RQ8xBCpH4JKdYvmIJ+6AQr9Y5mUC7L/hHOm4oRnIgBnSnoj/vN+nqvuZKn1h4DI8XnevuK4doOv9rX4rLz1gJPgvJKjgFrp/7NP/DyxEk2wamaZXT4xv3qx00LKszv4FG32r1RK8QDNP6MjMGUL7g90dD96kr0Z+KUGrjyptcqgTMUPoPax0VKIDaaEZ87J3cNl+KCxTj/SN582ifB2NN7fJlTF2u8n/bvELI+3f9PtElFF2oehVUsOw4J3q09lF5O5eI6kAOY5L4vnGzRWfpdnwMNmK/I+2u/scvA4cxKgdv9UT2FNlS7oSrm4omCgr/42AokCLoSB6gVOBrr1Cah2z+GQgC/J3pL6wigwmymnvLDNfiumkyBloE7rxcqZCnk5BBUbHPo/EISSTz+OEvRs8hjTDKPp3TV0xX2fE/I8tdXIqtD52WBTFQvqJuSgbdgi8rPBaHD04ZRhv4sF+kjiB1AwLlShTDEAVhzW9u4ZLEkNDgKFtMOgJGz0BF18/klxoFXYFvkz0DKB4J7f3ChoVPuWIPX7fheF9c1jm2uIU2l4o=
  template:
    metadata:
      creationTimestamp: null
      name: image-basic-secret
      namespace: infra
    type: kubernetes.io/dockerconfigjson
