apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-basic-secret
  namespace: infra
spec:
  encryptedData:
    .dockerconfigjson: AgAWAlrYOpny+vKDfuqt//Bra0wHuX0Ipjdkj9eSwdQEm+Cn29n0OkGwXr8ngDQ3rSfJxPlOC3zp9FrvDDcgMu8pJ060PYKDDOPS1WOb/OMFduWSsJLkLOGCEeu27TgI4vu9LF+PrASO4SzQ6S51pSlzjSw6p46OlKH5esL/OGMBPtY8OhWk8veWCdR+D9y87djkv6h2jaOY5NM1O3y9ULTfCBo+Vjx71ACUr9yMLBYjSXZsvuaJhlgkZJRq/brqf9Q0Mb06UP96uR82t6s69d614MhBYxi+WAopioF5cjUwMp+/+lwRtGEQkbBl5HJD75Uh5o8Gtyh3pRXovPiUSbtexL1daWwwd1sSDmiSdLPWHUPU5xEEfIKnsg+bmgAfBjEjTt0fIXUg4Jc87VV05gK6dcOfxmnBgAPkJr0lJTLhw0xq48PdZNn5CjYnfBJ15T+UUQGSdVMGCBeAs5l6mdui9CfXOGz9Bgm/yIdZ2eu7W16aQlr7XCm7XbG2+dJLbdZzLVkgOb5C23aTz4d5hAVhsc5jYETDC/5/PLUm+8nAavToLgkxvDFUlxBO6bBdDd+dprRjKNBXb7mmHilie/OYyF8TRiRqw1YbUHLvMyvjSGpPv/1Q72o3bG0t2CcR0srxhjWu1YQZBDeUUOD2V1fExYN9euZW70KEMCcTTQT+BzI9Sv+RJjX5cVJUPO2u49HyDwwVM6IXmquJIA6d0RRoIjRTqeKrbOdSKcLB/EeKqqd5646Lbv8/bP1wisU2gnKGsLIA0fkEIWztnW/vJIUzqI/s50Qc0ehMu4mFrthnSqVCZc7tm7QSOct2GknRuserj2a4vvWAjGbdWp7grxcU82KrdqYf0296IzxYR2G9TiCKY7DsaiYXr4RYJoj12i0SBQmpH6Gyn76T+kqfxBBX0rsDt9EIVg5RpEHevdE29jN6OrQpiqUimQk+pXhGuZV3IY4uVMFMjj2KDDc3I28=
  template:
    metadata:
      creationTimestamp: null
      name: image-basic-secret
      namespace: infra
    type: kubernetes.io/dockerconfigjson
