apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ankiba-build-binding.yaml
  - ankiba-build-pipeline.yaml
  - ankiba-build-template.yaml
  - ankiba-el-ingress.yaml
  - ankiba-listener.yaml
  - ankiba-web-build-binding.yaml
  - ankiba-web-build-pipeline.yaml
  - ankiba-web-build-template.yaml
  - ankiba-web-el-ingress.yaml
  - ankiba-web-listener.yaml
